# Generated by Django 5.1.7 on 2025-04-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('image', models.ImageField(upload_to='sample_images/', verbose_name='عکس پروژه')),
                ('link', models.URLField(verbose_name='لینک پروژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
            },
        ),
    ]
