# Generated by Django 5.1.7 on 2025-04-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplelist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام پروژه'),
        ),
    ]
