# Generated by Django 5.1.7 on 2025-04-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_samplelist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplelist',
            name='link',
            field=models.CharField(max_length=255, verbose_name='لینک پروژه'),
        ),
    ]
