# Generated by Django 5.1.7 on 2025-04-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'شخص', 'verbose_name_plural': 'اشخاص'},
        ),
    ]
