# Generated by Django 5.1.7 on 2025-04-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about_us_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن درباره ما'),
        ),
    ]
