# Generated by Django 5.1.7 on 2025-04-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_person_about_us_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('percent', models.IntegerField(verbose_name='درصد مهارت')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='about_us_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن درباره من'),
        ),
    ]
