# Generated by Django 5.1.7 on 2025-04-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_skills_alter_person_about_us_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('mail', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('telegram_link', models.CharField(max_length=255, verbose_name='لینک تلگرام')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس ها',
            },
        ),
    ]
