# Generated by Django 5.1.7 on 2025-04-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tahsilat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_university', models.CharField(max_length=255, verbose_name='نام دانشگاه')),
                ('name_reshte', models.CharField(max_length=255, verbose_name='نام رشته')),
                ('zaman_tahsil', models.CharField(max_length=255, verbose_name='زمان تحصیل')),
                ('pic', models.ImageField(upload_to='daneshgah/', verbose_name='عکس دانشگاه')),
            ],
            options={
                'verbose_name': 'تحصیل',
                'verbose_name_plural': 'تحصیلات',
            },
        ),
    ]
