# Generated by Django 5.1.7 on 2025-04-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavabeghKari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kari', models.CharField(max_length=255, verbose_name='عنوان کاری')),
                ('mahl_kari', models.CharField(max_length=255, verbose_name='محل کار')),
                ('zaman_kar', models.CharField(max_length=255, verbose_name='زمان کار')),
                ('pic', models.ImageField(upload_to='savabegh/', verbose_name='عکس کار')),
            ],
        ),
    ]
