# Generated by Django 5.1.7 on 2025-04-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_savabeghkari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zaban', models.CharField(max_length=255, verbose_name='نام زبان')),
                ('percent', models.IntegerField(verbose_name='درصد تسلط')),
            ],
            options={
                'verbose_name': 'زبان',
                'verbose_name_plural': 'زبان ها',
            },
        ),
        migrations.AlterModelOptions(
            name='savabeghkari',
            options={'verbose_name': 'کار', 'verbose_name_plural': 'محل های کار'},
        ),
    ]
