# Generated by Django 5.1.7 on 2025-05-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_zaban_alter_savabeghkari_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Madarek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_madrak', models.CharField(max_length=255, verbose_name='نام مدرک')),
                ('sader_konande', models.CharField(max_length=200, verbose_name='صادر کننده')),
                ('date', models.CharField(max_length=50, verbose_name='تاریخ صدور')),
                ('link', models.URLField(verbose_name='لینک مدرک')),
            ],
        ),
    ]
