# Generated by Django 5.1.7 on 2025-05-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_madarek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='madarek',
            options={'verbose_name': 'مدرک', 'verbose_name_plural': 'مدارک'},
        ),
    ]
